[09:30:10 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[09:30:31 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[09:30:55 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:16:09 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:16:13 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:17:39 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:18:02 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:19:55 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:20:14 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:20:59 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:21:11 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:21:34 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:21:34 22-01-2018] (Error) dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:22:39 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:23:48 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:24:35 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:24:49 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:25:00 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:26:16 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:26:38 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:26:46 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:27:17 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:27:34 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:27:49 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:43:14 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.15: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[23:33:06 22-01-2018] (Success) server.py::logout.114: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[23:33:32 22-01-2018] (Success) server.py::logout.114: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[23:38:31 22-01-2018] (Success) server.py::logout.120: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[08:51:52 23-01-2018] (Success) server.py::logout.120: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
